Feature/task responsive
so-suke/moovon_10_coding_task pull request #6
Opened 2019-03-13 17:07 UTC by so-suke

主にやったこと
・色の名前を新たに定義し直しました。
・レスポンシブ対応のためのmixinを作成しました。
・幅979pxからの「ヘッダーナビを切り替える」処理の作成
・幅979pxから表示される「ブログ記事カラム」の作成
心配な点
・ヘッダーナビのネストが深いかもしれません。
・幅979pxからの「ヘッダーナビ」の枠線定義が若干複雑かもしれません。

2019-03-14 14:14 UTC, s-higu requested changes

2019-03-14 14:14 UTC, s-higu commented on index.html
> +      <ul class="column__basicList">
クラス名をわけた理由はなんでしょう🤔
状態がちがうものを定義したい時はどうすればよかったでしたっけ！

2019-03-14 14:14 UTC, higusyun commented on scss/variables/_variables.scss
> +$paletteWhite: #fff;
`palette` と `color` にはどんな違いがありますかね？
説明がつかないのであれば統一しましょう（colorのほうがいいです）

2019-03-14 14:14 UTC, higusyun commented on scss/components/_btn.scss
> +		 color: $paletteWhite;
インデントはそろえましょう！

2019-03-14 14:14 UTC, higusyun commented on scss/components/_footer.scss
> +      @include breakMinWidth($breakpointLarge + 1) {
`+1` してるのは何故でしょう🤔

2019-03-14 14:14 UTC, higusyun commented on scss/components/_footer.scss
> +				width: 90%;
インデント

2019-03-14 14:14 UTC, higusyun commented on scss/components/_list.scss
> +        height: 60px;
文字に余白があるわけなので、 `li` の `padding` として定義しましょう。
`absolute` したり領域を定めたい場合をのぞいては `height` は原則使わないようにしましょう。

2019-03-14 14:14 UTC, higusyun commented on scss/components/_list.scss
> +        display: flex;
このへん全体的に重複したスタイルを書きすぎちゃってるので、メディアクエリ内で同じ内容を打ち消さないようにしましょう！

2019-03-14 14:14 UTC, higusyun commented on scss/components/_list.scss
> +  &.column__basicList {
PCでもブログが見えちゃってるので要修正で！

2019-03-18 17:27 UTC, so-suke commented on scss/components/_footer.scss
> +      @include breakMinWidth($breakpointLarge + 1) {
PCサイズ(980px以上)のみで定義したいものが、あったためです。
`$breakpointLarge: 979px;` ですので `+1` しました。
認識間違いがありましたらご指摘ください。

2019-03-18 17:30 UTC, so-suke commented on index.html
> +      <ul class="column__basicList">
ありがとうございます。
bemのmodifierでした。
`column__list--basic` に修正しました。

2019-03-18 17:30 UTC, so-suke commented on scss/variables/_variables.scss
> +$paletteWhite: #fff;
colorに統一しました。

2019-03-18 17:33 UTC, so-suke commented on scss/components/_btn.scss
> +		 color: $paletteWhite;
githubに上げると稀にそのように、なってしまいます。
push前にエディタ側でインデントを揃え直すようにします。

2019-03-18 17:36 UTC, so-suke commented on scss/components/_list.scss
> +        height: 60px;
ありがとうございます。paddingに修正しました。
heightの固定値は、変化に弱い様なので、あまり使用しない方がいいようですね。

2019-03-18 17:37 UTC, so-suke commented on scss/components/_list.scss
> +  &.column__basicList {
ありがとうございます。修正しました。

2019-03-22 04:11 UTC, s-higu requested changes

2019-03-22 04:11 UTC, higusyun commented on scss/components/_footer.scss
> +        right: 0;
`right` 打ち消して `left` を追記するのであれば下記のほうがシンプルになります
```
right: 50%;
transform: translateX(50%);
```

2019-03-22 04:11 UTC, higusyun commented on index.html
> +      <ul class="column__list column__list--basic">
`basic` はどんな意味でつけてますか？

2019-03-24 21:34 UTC, merged